server:
  port: 18086
feign:
  sentinel:
    enabled: true
logging:
  level:
    com.atguigu.gmall: debug
spring:
  elasticsearch:
    rest:
      uris: http://192.168.58.131:9200
  jackson:
    default-property-inclusion: non_null
  thymeleaf:
    cache: false
  rabbitmq:
    host: 192.168.58.131
    virtual-host: /xiaoliu
    username: xiaoliu
    password: xiaoliu
    listener:
      simple:
        prefetch: 1
        acknowledge-mode: manual
        concurrency: 3