server:
  port: 18086
feign:
  sentinel:
    enabled: true
logging:
  level:
    com.atguigu.gmall: debug
spring:
  elasticsearch:
    rest:
      uris: http://192.168.58.131:9200
  jackson:
    default-property-inclusion: non_null