server:
  port: 18088
feign:
  sentinel:
    enabled: true

logging:
  level:
    com.atguigu.gmall: debug
threadPool:
  coreSize: 100
  maxsize: 500
  keepAlive: 60
  blockingSize: 5000
spring:
  thymeleaf:
    cache: false