server:
  port: 18085
feign:
  sentinel:
    enabled: true
mybatis-plus:
  mapper-locations: classpath:mapper/wms/*.xml  # \u8BFB\u53D6\u6620\u5C04\u6587\u4EF6
  type-aliases-package: com.atguigu.gmall.wms.entity
  global-config:
    db-config:
      id-type: auto
spring:
  rabbitmq:
    host: 192.168.58.131
    virtual-host: /xiaoliu
    username: xiaoliu
    password: xiaoliu
    listener:
      simple:
        prefetch: 1
        concurrency: 3
        acknowledge-mode: manual
    publisher-returns: true
    publisher-confirm-type: correlated