server:
  port: 18085
feign:
  sentinel:
    enabled: true
mybatis-plus:
  mapper-locations: classpath:mapper/wms/*.xml  # \u8BFB\u53D6\u6620\u5C04\u6587\u4EF6
  type-aliases-package: com.atguigu.gmall.wms.entity
  global-config:
    db-config:
      id-type: auto
